name: function-approximation-nn
dependencies:
  - python>=3.6
  - pip
  - pip:
    - torch>=1.1.0
    - torchvision>=0.2.2
    - pytorch-lightning==0.4.8
    - tqdm>=4.35.0
    - brontes==0.0.2
    - mlflow>=1.2.0
    - flake8>=3.7.8
    - yapf>=0.28.0
